### ISSUE TITLE
To-Do list

### ISSUE THREAD

**Issue by hhkaos** [GeoVoluntarios-org/geonight#16]
- [x] Embed game hints
- [x] Calculate the time to answer
- [x] Require a user login and save time and answers for each user
- [x] Add real answers
- [x] Uncheck already answered locations
- [x] Calculate error with respect to the selected location
- [x] Add final question
- [x] Stop clock, thank you and return to web
- [x] Save already sent answers
- [x] Check application status when loading (if already finished don't let play any more)
- [x] Ask for names of team members at startup
- [x] Send answers to server
- [x] Change final question -> Open and compare similarity with valid answers
- [x] Update hint videos
- [ ] Improve UI:
  - [x] Fix iframe Size.
  - [x] Add links to images for large view
  - [x] Add animation when mousing over track
- [x] Improve startup instructions (add screenshot of the interface)
- [x] Change auth0 data with data from Terra Incognita
- [x] UI: Flip when clicking
- [x] Accumulated is not shown after registration
- [x] Download answers
- [x] Add zoom to image
- [ ] Add [catch to applyEdits](https://developers.arcgis.com/javascript/latest/sample-code/editing-applyedits/) in case it fails to save
- [ ] TOS
